version: '3.8'

services:
  database:
    image: mysql:8.4.0
    container_name: mysql-cotizador
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cotizador_marmoleria
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: